import dotenv from 'dotenv'; import path from 'node:path'; import { fileURLToPath } from 'node:url'; import express from 'express'; import cors from 'cors'; import mongoose from 'mongoose'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import crypto from 'crypto'; import twilio from 'twilio'; import { z } from 'zod'; import { Application, Job, Otp, User } from './models.js'; import { allow, auth } from './middleware.js';
dotenv.config({path:path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../.env')});
const app=express(),port=process.env.PORT||4000,twilioReady=!!(process.env.TWILIO_ACCOUNT_SID&&process.env.TWILIO_AUTH_TOKEN&&process.env.TWILIO_VERIFY_SERVICE_SID);const twilioClient=twilioReady?twilio(process.env.TWILIO_ACCOUNT_SID,process.env.TWILIO_AUTH_TOKEN):null;
app.use(cors({origin:process.env.CORS_ORIGIN||'http://localhost:5173'}));app.use(express.json());
const publicUser=u=>({id:u._id,name:u.name,email:u.email,phone:u.phone,role:u.role,headline:u.headline,location:u.location,skills:u.skills,completion:u.completion,alerts:u.alerts});
const phone=z.string().regex(/^\+[1-9]\d{7,14}$/,'Use E.164 format, e.g. +919876543210.');const credentials=z.object({email:z.string().email(),password:z.string().min(8)});const registration=credentials.extend({name:z.string().min(2).max(80),phone,role:z.enum(['candidate','recruiter'])});
async function issueOtp(user,purpose){if(twilioReady){await twilioClient.verify.v2.services(process.env.TWILIO_VERIFY_SERVICE_SID).verifications.create({to:user.phone,channel:'sms'});return}if(process.env.NODE_ENV==='production')throw new Error('Twilio Verify credentials are required in production.');await Otp.deleteMany({email:user.email});const code=crypto.randomInt(100000,1000000).toString();await Otp.create({email:user.email,codeHash:await bcrypt.hash(code,10),purpose,expiresAt:new Date(Date.now()+5*60e3)});console.log(`[Careerflow DEV OTP] ${user.phone}: ${code}`)}
async function confirmOtp(user,code){if(twilioReady){const result=await twilioClient.verify.v2.services(process.env.TWILIO_VERIFY_SERVICE_SID).verificationChecks.create({to:user.phone,code});return result.status==='approved'}const otp=await Otp.findOne({email:user.email}).sort({createdAt:-1});const valid=!!otp&&otp.expiresAt>new Date()&&await bcrypt.compare(code,otp.codeHash);if(valid)await Otp.deleteMany({email:user.email});return valid}
app.post('/api/auth/register',async(req,res,next)=>{try{const data=registration.parse(req.body);if(await User.exists({$or:[{email:data.email.toLowerCase()},{phone:data.phone}]}))return res.status(409).json({message:'An account already exists for this email or phone number.'});const user=await User.create({name:data.name,email:data.email,passwordHash:await bcrypt.hash(data.password,12),phone:data.phone,role:data.role,headline:data.role==='candidate'?'Professional seeking their next opportunity':'Recruiting exceptional talent'});await issueOtp(user,'register');res.status(201).json({message:'OTP sent by SMS.'})}catch(e){next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const data=credentials.parse(req.body);const user=await User.findOne({email:data.email.toLowerCase()});if(!user||!await bcrypt.compare(data.password,user.passwordHash))return res.status(401).json({message:'Email or password is incorrect.'});if(!user.phone)return res.status(400).json({message:'This account has no verified mobile number. Register again or contact support.'});await issueOtp(user,'login');res.json({message:'OTP sent by SMS.'})}catch(e){next(e)}});
app.post('/api/auth/verify-otp',async(req,res,next)=>{try{const data=z.object({email:z.string().email(),code:z.string().regex(/^\d{6}$/)}).parse(req.body);const user=await User.findOne({email:data.email.toLowerCase()});if(!user||!await confirmOtp(user,data.code))return res.status(400).json({message:'Invalid or expired OTP.'});const token=jwt.sign({sub:user._id.toString(),role:user.role},process.env.JWT_SECRET,{expiresIn:'8h'});res.json({token,user:publicUser(user)})}catch(e){next(e)}});
app.get('/api/auth/me',auth,async(req,res)=>res.json(publicUser(await User.findById(req.user.sub))));
app.get('/api/jobs',async(req,res)=>res.json(await Job.find({active:true}).sort({createdAt:-1}).lean()));app.post('/api/jobs',auth,allow('recruiter','admin'),async(req,res,next)=>{try{const data=z.object({title:z.string().min(3),companyName:z.string().min(2),location:z.string().min(2),workMode:z.enum(['Remote','Hybrid','On-site']),skills:z.array(z.string()).min(1)}).passthrough().parse(req.body);res.status(201).json(await Job.create({...data,recruiter:req.user.sub}))}catch(e){next(e)}});
app.post('/api/jobs/:id/applications',auth,allow('candidate'),async(req,res,next)=>{try{const job=await Job.findById(req.params.id);if(!job)return res.status(404).json({message:'Job not found'});res.status(201).json(await Application.create({job:job._id,candidate:req.user.sub}))}catch(e){next(e)}});app.get('/api/applications',auth,async(req,res)=>res.json(await Application.find(req.user.role==='candidate'?{candidate:req.user.sub}:{}).populate('job candidate').sort({createdAt:-1})));app.patch('/api/applications/:id/status',auth,allow('recruiter','admin'),async(req,res,next)=>{try{const status=z.enum(['Applied','Reviewed','Shortlisted','Interview Scheduled','Hired','Rejected']).parse(req.body.status);res.json(await Application.findByIdAndUpdate(req.params.id,{status},{new:true}))}catch(e){next(e)}});
app.use((err,req,res,next)=>{if(err instanceof z.ZodError)return res.status(400).json({message:'Invalid request',issues:err.flatten()});console.error(err);res.status(500).json({message:'Unexpected server error'})});if(!process.env.MONGODB_URI||!process.env.JWT_SECRET){console.error('Set MONGODB_URI and JWT_SECRET in the project-root .env file.');process.exit(1)}if(process.env.NODE_ENV==='production'&&!twilioReady){console.error('Set Twilio Verify credentials before running in production.');process.exit(1)}mongoose.connect(process.env.MONGODB_URI).then(async()=>{try{await mongoose.connection.db.createCollection('_careerflow')}catch(e){if(e.codeName!=='NamespaceExists')throw e}app.listen(port,()=>console.log(`Careerflow API on http://localhost:${port} (${twilioReady?'Twilio SMS enabled':'development OTP console'})`))}).catch(e=>{console.error('MongoDB connection failed:',e.message);process.exit(1)});
